"""description of changes

Revision ID: 34b9b553bb67
Revises: f8ef9e33fe4e
Create Date: 2024-04-18 19:31:14.138709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b9b553bb67'
down_revision: Union[str, None] = 'f8ef9e33fe4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sleep_goal', sa.Integer(), nullable=True))
    op.drop_column('users', 'sleep')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sleep', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'sleep_goal')
    # ### end Alembic commands ###
