"""Initial migration

Revision ID: 3fab862670ae
Revises: 
Create Date: 2024-03-23 17:53:31.149228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fab862670ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
                    sa.Column('username', sa.String(), nullable=False, unique=True),
                    sa.Column('password', sa.String(), nullable=False),
                    )
    op.create_table('activities',
                    sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
                    sa.Column('description', sa.String(), nullable=False),
                    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('users')
    # ### end Alembic commands ###

