"""Added DailyPlan entity and updated User relationships

Revision ID: 64e97736bcda
Revises: ee55400be01f
Create Date: 2024-04-12 12:07:21.127488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e97736bcda'
down_revision: Union[str, None] = 'ee55400be01f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Enum('Male', 'Female', 'Other', name='sex_types'), nullable=True),
    sa.Column('sleep', sa.Integer(), nullable=True),
    sa.Column('first_login_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dailyplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sleep', sa.Integer(), nullable=True),
    sa.Column('outside_time', sa.Integer(), nullable=True),
    sa.Column('productive_time', sa.Integer(), nullable=True),
    sa.Column('exercise', sa.Integer(), nullable=True),
    sa.Column('screen_time', sa.Integer(), nullable=True),
    sa.Column('other_activities', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailyplans')
    op.drop_table('activities')
    op.drop_table('users')
    # ### end Alembic commands ###
