"""Added age, sex, sleep to User

Revision ID: c1d4153a5778
Revises: 7bb314d8f3e6
Create Date: 2024-04-04 16:20:07.214776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d4153a5778'
down_revision: Union[str, None] = '7bb314d8f3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sex', sa.Enum('Male', 'Female', 'Other', name='sex_types'), nullable=True))
    op.add_column('users', sa.Column('sleep', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sleep')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
