"""new columns for user

Revision ID: f8ef9e33fe4e
Revises: 61f6e19ae6aa
Create Date: 2024-04-18 19:21:04.379702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ef9e33fe4e'
down_revision: Union[str, None] = '61f6e19ae6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exercise_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('outside_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('productive_goal', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('screen_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'screen_goal')
    op.drop_column('users', 'productive_goal')
    op.drop_column('users', 'outside_goal')
    op.drop_column('users', 'exercise_goal')
    # ### end Alembic commands ###
